### ISSUE TITLE
Check the coloring of enclosed expressions

### ISSUE THREAD

**Issue by wcandillon** [wcandillon/language-jsoniq#13]
https://www.dropbox.com/s/2uka298be3ls41x/Screenshot%202015-06-08%2018.14.41.png?dl=0

This is due to the nesting of highlighting rules in Atom.

**Comment by ruv** [comment]
It sees that this issue is not reproducible anymore.
![language-xquery-coloring](https://cloud.githubusercontent.com/assets/2678296/12389504/44ace922-bdea-11e5-8718-91615b6ecf1e.png)

Atom 1.4.0, language-jsoniq 1.7.6

**Comment by wcandillon** [comment]
@ruv awesome!
