### ISSUE TITLE
Snippets are not available for XQuery language

### ISSUE THREAD

**Issue by ruv** [wcandillon/language-jsoniq#15]
There is not any snippet available for XQuery file type. Although, if JSONiq file type is selected, all the snippets are available.

The following screenshots are made on pressing Alt+Shift+S (note the selected file type in the bottom-right corner):
![language-xquery-snippets](https://cloud.githubusercontent.com/assets/2678296/12388588/c9b6b284-bde4-11e5-82a1-f521388f7b4c.png)
![language-jsoniq-snippets](https://cloud.githubusercontent.com/assets/2678296/12388595/d6bdfc30-bde4-11e5-8816-5524c5cf126f.png)

Atom 1.4.0, language-jsoniq 1.7.6

**Comment by wcandillon** [comment]
Should be fixed in v1.7.8, let me know if this didn't work.
